### PR TITLE
Nodes updated

### PR DESCRIPTION
**Pull request by MirhasVida**

### CODE REVIEW

**Comment by MirhasVida** [comment]
Is there any problem that it shows that there are 32 commits ahead?
I know that commits behind makes some crashes, but I'm not sure about commits ahead

**Comment by myangelkamikaze** [comment]
It's not really a problem, no. But you could [sync](https://docs.github.com/ko/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-web-ui) your repository before making changes.

Also, it seems like we're not using the nodes.json file, so that should actually just get deleted.

**Comment by myangelkamikaze** [comment]
Closing this PR because we deleted nodes.json because it's not actually used anymore.

**Comment by MirhasVida** [comment]
Got it!

**Pull request closed without merging**
