### PR TITLE
Korean Translation

### PR DESCRIPTION
**Pull request by MirhasVida**
Check it out!

### CODE REVIEW

**Comment by myangelkamikaze** [comment]
Jebzou added some missing equipment, so you'll need to update your fork with the changes before I can merge.

**Comment by myangelkamikaze** [comment]
Also, I forgot to mention it, you'll need to raise the version in [update,json](https://github.com/ElectronicObserverEN/Data/blob/master/Translations/ko-KR/update.json#L2) so that Electronic Observer can know the files were updated.

You can also test the changes locally by changing the translation url. In your case you'd replace it with https://raw.githubusercontent.com/MirhasVida/Data/master/.
image

**Comment by myangelkamikaze** [comment]
I also just remembered that some [translations](https://github.com/TheLokis/EOTranslation) exist from a different Korean fork, in case that makes things easier for you.

**Comment by MirhasVida** [comment]
> I also just remembered that some [translations](https://github.com/TheLokis/EOTranslation) exist from a different Korean fork, in case that makes things easier for you.

Thank you for mentioning it, but it's too old to apply here... So I think I should do it from the bottom

**Comment by myangelkamikaze** [comment]
To fix the merge conflict click here:
image

Delete those parts and make sure there's a , at the end.
image

**Pull request closed without merging**
