### PR TITLE
Update Locks

### PR DESCRIPTION
**Pull request by MirhasVida**

### CODE REVIEW

**Comment by myangelkamikaze** [comment]
You should update the [lock version](https://github.com/MirhasVida/Data/blob/master/Translations/ko-KR/update.json#L9) too.

**Comment by MirhasVida** [comment]
Solved! Btw, I've added quotation marks for the locks version, if it doesn't needed, I'll fix it.

**Comment by myangelkamikaze** [comment]
Quotation marks will change the version from an integer to a string, which will break the parsing logic in EO, so you need to remove them yeah.
Others need to stay as string though, it's a minor inconsistency though, yeah.

**Comment by myangelkamikaze** [comment]
Since you also updated quests now, you'll need to update the [quest version](https://github.com/MirhasVida/Data/blob/master/Translations/ko-KR/update.json#L6) too.

**Comment by MirhasVida** [comment]
Oh I'm not fully updated it yet so would you update it without quests?

**Comment by myangelkamikaze** [comment]
I can't select which parts get updated, you'd have to undo the change on your branch.
But it doesn't matter if it's not fully updated yet, you can make updates in multiple parts, it's not a problem.

**Pull request merged**
