### PR TITLE
Data/ShipClass.json

### PR DESCRIPTION
**Pull request by MirhasVida**
I think I've already made a PR for this update, however, I think that it does not apply yet or there are some more updates here. What version do I have to follow?

### CODE REVIEW

**Comment by myangelkamikaze** [comment]
[ship](https://github.com/MirhasVida/Data/blob/master/Translations/ko-KR/update.json#L7)

**Comment by myangelkamikaze** [comment]
Oh, and yeah, some ship translations were missing in the Korean translation file. Jebzou added the missing data.

**Comment by MirhasVida** [comment]
Checked!

**Comment by myangelkamikaze** [comment]
Uhh?

**Comment by MirhasVida** [comment]
Is there any problem???

**Comment by myangelkamikaze** [comment]
You closed the PR?

**Comment by myangelkamikaze** [comment]
Ah, you made a new PR.
If you make new changes, they should show up in the existing PR, so there's no need to close it and open a new one.

**Comment by MirhasVida** [comment]
I got it! Thanks

**Pull request closed without merging**
