### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by MirhasVida**

### CODE REVIEW

**Comment by myangelkamikaze** [comment]
You'll need to resolve the conflicts before I can merge this.

**Comment by MirhasVida** [comment]
Solved

**Comment by myangelkamikaze** [comment]
You should also raise the version of [equipment](https://github.com/ElectronicObserverEN/Data/blob/51aca677c9ef10789f0f5328a45274fc65a1cecc/Translations/ko-KR/update.json#L2) so that EO will detect the change.

**Comment by MirhasVida** [comment]
Is this right?

**Comment by myangelkamikaze** [comment]
Yes, thanks for the translations!

**Pull request merged**
